spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: "postgres"
    password: "12345"
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update